### ISSUE TITLE
Building on Ubuntu: "Unbound module GSourceView2"

### ISSUE THREAD

**Issue by dolmen** [sgimenez/laby#34]
I'm trying to build from source on Ubuntu 14.04.
I've installed the following Ubuntu packages:

* `ocaml`
* `ocaml-findlib`
* `liblablgtk2-ocaml`
* `liblablgtk2-ocaml-dev`

But I get this error when building:
```
$ make
Building laby-0.6.4 for linux-amd64
+ /usr/bin/ocamlopt -c -I /usr/lib/ocaml/lablgtk2 -g -I src -I src/dtools -o src/gfx.cmx src/gfx.ml
File "src/gfx.ml", line 79, characters 17-41:
Error: Unbound module GSourceView2
Command exited with code 2.
Compilation unsuccessful after building 81 targets (0 cached) in 00:00:02.
make: *** [all] Erreur 1
```

How can I get `GSourceView2`?

**Comment by sgimenez** [comment]
You need `liblablgtksourceview-ocaml-dev` as well!

**Comment by dolmen** [comment]
Thanks. The right package is `liblablgtksourceview2-ocaml-dev`.
