### ISSUE TITLE
I try to build this in my computer but there is a error

### ISSUE THREAD

**Issue by ishamo** [sgimenez/laby#37]
q@ubuntu:~/github/laby$ ./build 
Building laby-0.6.4 for linux-amd64
+ /usr/bin/ocamlopt -c -I /usr/lib/ocaml/lablgtk2 -g -I src -I src/dtools -o src/gfx.cmx src/gfx.ml
File "src/gfx.ml", line 79, characters 17-41:
Error: Unbound module GSourceView2
Command exited with code 2.
Compilation unsuccessful after building 81 targets (80 cached) in 00:00:00.

--------------------------
I like this game and wan't to translate it into Chinese. Would you please help me to see where is wrong? Thanks a lot.

**Comment by sgimenez** [comment]
See here: https://github.com/sgimenez/laby/issues/34
