### ISSUE TITLE
Version for Fedora and other characteristics

### ISSUE THREAD

**Issue by AndersonFirmino** [sgimenez/laby#41]
I like this game since we always know linux play him, I am currently using Fedora version and have not found him. I will try to make a version of the code here to run it.

But if you have anything please tell me. : D

**Comment by sgimenez** [comment]
Nothing is specific to Fedora in the repository, but it should not be too hard to compile on Fedora. It might also be possible to import the Ubuntu package?

Hope you will manage to make it work!

**Comment by sandrobonazzola** [comment]
Review request for Fedora inclusion:  https://bugzilla.redhat.com/show_bug.cgi?id=1450679
Copr repository: https://copr.fedorainfracloud.org/coprs/sbonazzo/Laby/
