### ISSUE TITLE
Please port the code to use getaddrinfo().

### ISSUE THREAD

**Issue by sandrobonazzola** [sgimenez/laby#49]
While trying to port laby to OpenSuse, automated check detects:
laby.x86_64: I: binary-or-shlib-calls-gethostbyname /usr/bin/laby
The binary calls gethostbyname(). Please port the code to use getaddrinfo().

See https://en.opensuse.org/openSUSE:Packaging_checks#binary-or-shlib-calls-gethostbyname
and http://udrepper.livejournal.com/16116.html about why this is raised.

OpenSuse Tumbleweed build is available on https://build.opensuse.org/package/show/home:sandrobonazzola/laby

**Comment by sgimenez** [comment]
It's not a problem with laby itself, it likely comes from *ocaml* itself (or possibly *lablgtk*). The symbols appears to be linked in the binary but I doubt it's ever called.
