### ISSUE TITLE
Build failure in Fedora 28 mass rebuild

### ISSUE THREAD

**Issue by sandrobonazzola** [sgimenez/laby#53]
Rebuilding laby on Fedora 28 fails with:
+ /usr/bin/ocamlopt.opt -c -I /usr/lib64/ocaml/lablgtk2 -g -I src -I src/dtools -o src/mod.cmx src/mod.ml
File "src/mod.ml", line 97, characters 13-26:
Warning 3: deprecated: String.create
Use Bytes.create instead.
File "src/mod.ml", line 101, characters 23-29:
Error: This expression has type bytes but an expression was expected of type
         string
Command exited with code 2.
make: *** [Makefile:20: native] Error 1

**Comment by sandrobonazzola** [comment]
Fedora trackiing bug: https://bugzilla.redhat.com/show_bug.cgi?id=1556013

**Comment by sandrobonazzola** [comment]
I can workaround that by setting -unsafe-string via the `OCAMLPARAM environment variable:

export OCAMLPARAM="safe-string=0,_"

**Comment by sandrobonazzola** [comment]
Suggested patch to spec file attached to the bug: https://bugzilla.redhat.com/attachment.cgi?id=1409487
The patch implements above workaround but a fix to the laby code would be better.

**Comment by sgimenez** [comment]
This should be fixed now. Many years have passed, but I'll try to make a new release soon (mainly to address the lablgtk2/sourceview2 obsolescence).
