### ISSUE TITLE
laby fails to build due to unsafe string 

### ISSUE THREAD

**Issue by sandrobonazzola** [sgimenez/laby#59]
On Fedora Rawhide laby fails to build with:

+ /usr/bin/ocamlc.opt -c -I /usr/lib64/ocaml/lablgtk2 -g -I src/dtools -I src -o src/dtools/conf.cmi src/dtools/conf.mli
File "src/dtools/conf.mli", line 1:
Error: Invalid import of F, compiled with -unsafe-string.
       This compiler has been configured in strict safe-string mode (-force-safe-string)
Command exited with code 2.
make: *** [Makefile:20: native] Error 1

the compiler there doesn't allow unsafe strings.

**Comment by sgimenez** [comment]
I think this has been resolved already. Using "make clean" after an OCaml upgrade shoud be enough.
